#!/usr/bin/env bash

# Убиваем старые инстансы
killall -q polybar

# Ждем пока процессы завершатся
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Запускаем polybar на всех мониторах
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload mybar &
  done
else
  polybar --reload mybar &
fi

echo "Polybar запущен..."
