#!/bin/bash
while true
do
a=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep perc);
bat=${a//    percentage:          /};
sound=$(amixer -c 0 sget Master |awk '/Mono:/ {print($6$4)}');
time=$(date '+%H:%M:%S');


xsetroot -name "  $bat | $sound | $time";
sleep 2;
done;
